version: "3.8"
services:
    client:
        build: ./client
        image: dashboard-client
        container_name: dashboard-client
        ports:
            - "81:80"
        expose:
            - "81"
        restart: unless-stopped
        networks:
            - front-tier

    server:
        build: ./server
        image: dashboard-server
        container_name: dashboard-server
        environment:
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: postgres
        ports:
            - "8080:8080"
        expose:
            - "8080"
        restart: unless-stopped
        networks:
            - front-tier
            - back-tier

    db:
        image: postgres:9.4
        container_name: dashboard-databs
        volumes:
            - "dashboard-db-data:/var/lib/postgresql/data"
            - "./schema.sql:/docker-entrypoint-initdb.d/init.sql"
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        expose:
            - "5432"
        restart: unless-stopped
        networks:
            - back-tier

networks:
    front-tier:
    back-tier:

volumes:
    dashboard-db-data:
